name: AEenv
channels:
    - pytorch
    - conda-forge
dependencies:
    - numpy=1.26.3
    - pandas=2.2.0
    - pytorch=2.4.1
    - python=3.12.0
    - scikit-learn=1.3.0
    - torchvision=0.19.1
    - tqdm=4.66.1
    - pythae=0.1.2
    - matplotlib=3.8.2
